### ISSUE TITLE
Cario-features.h error while complining

### ISSUE THREAD

**Issue by ghost** [Youlean/WDL-Youlean#5]
![capture](https://user-images.githubusercontent.com/10063554/29123885-0b33d4fc-7d39-11e7-9eec-ac2ef620fc91.PNG)
"Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'GL/glew.h': No such file or directory	IPlug	c:\iplug-youlean-master\ycairo\cairo_graphics\projects\cairo\src\cairo-features.h	37"

 any solution?

**Comment by Youlean** [comment]
Just comment it out. I was experimenting with cairo GL but no luck so far...

**Comment by ghost** [comment]
Is the cario/wdl implementation working in windows? now getting can not find cario-win32-debug.lib error.

**Comment by Youlean** [comment]
Yes, but you need to compile every library separately. Open cairo project and switch to win32 debug and compile. Open IPlug-Youlean/YCAIRO/Cairo_Graphics/projects/cairo.sln and compile.

**Comment by olilarkin** [comment]
I had trouble with visual studio 2017, because when it read targets the solution, it doesn't properly upgrade the SDK setting. it was stuck on Windows 8.1, even though I'd asked it to upgrade 2 10.x. I had to modify the vcxproj files in a text editor to fix it

**Comment by olilarkin** [comment]
I'm still left with an opengl related error,which I hope to fix soon

**Comment by Youlean** [comment]
What is the problem with opengl? Does commenting glew.h works?

**Comment by olilarkin** [comment]
I had comment it and also remove GL / Glew from the library vcxproj

**Comment by Youlean** [comment]
Hm, then I am not sure why it won't compile. Unfortunately I am on vacation and I won't be able to look at the code until next sunday...

I will definitely include libs for windows in the future.

**Comment by olilarkin** [comment]
it's okay it's sorted now. have you heard about vcpkg? might be an easier way to work with cairo

**Comment by Youlean** [comment]
Great. I have seen vcpkg but haven't had time to check it out. 

Well ideally I would like to have projects for cairo so I can compile opengl backend and support for arm. 
Visual studio has a way to build c++ apps for android and ios so the plan is to leverage this in the future.

**Comment by meem40** [comment]
https://github.com/vurtun/nuklear this looks like a good alternative to cario
